UPDATE hr.users
SET
    can_access = '{"report__zipper_production":["read","show_own_orders"],"report__thread_production_batch_wise":["read","show_own_orders"],"report__thread_production_order_wise":["read","show_own_orders"],"report__daily_challan":["read","show_own_orders"],"report__pi_register":["read","show_own_orders"],"report__pi_to_be_submitted":["read","show_own_orders"],"report__lc_due":["read","show_own_orders"],"report__daily_production":["read","show_own_orders"],"report__production_statement":["read","show_own_orders"],"report__bulk":["read","show_price_pi","show_own_orders"],"report__orders":["read","show_own_orders"],"report__approved_orders":["read","show_own_orders"],"report__challan_status":["read","show_own_orders"],"report__order_summary":["read","show_own_orders"],"report__out_for_delivery":["read"],"order__details":["read","click_order_number","click_item_description","show_own_orders","show_price"],"order__details_by_order_number":["read"],"order__details_by_uuid":["read"],"order__order_pricing":["read","show_own_orders","edit_mkt_price"],"thread__order_info_details":["read","click_order_number","click_item_description","show_own_orders","show_price","show_cash_bill_lc"],"thread__order_info_in_details":["read","show_price","show_cash_bill_lc"],"commercial__lc":["read","show_own_orders"],"commercial__lc_details":["read","show_own_orders"],"commercial__pi":["read","show_own_orders"],"commercial__pi_details":["read","show_own_orders"],"commercial__manual_pi":["read","show_own_orders"],"commercial__manual_pi_details":["read"],"commercial__pi-cash":["read","show_own_orders"],"commercial__pi_cash_details":["read","show_own_orders"],"planning__finishing_batch_details":["read"],"dyeing__zipper_batch_details":["read"],"dyeing__thread_batch_details":["read"],"delivery__challan":["read","show_own_orders"],"delivery__challan_details":["read","show_own_orders"],"marketing__dashboard":["read"],"marketing__teams":["read"],"marketing__targets":["read"]}'
WHERE
    email NOT IN (
        'azam@fortunezip.com',
        'marketing-director@fortunezip.com',
        'sumya@fortunezip.com'
    )
    AND department_uuid = 'igD0v9DIJQhQeey';